### PR TITLE
Void Magnet Gene

### PR DESCRIPTION
**Pull request by tralezab**
you don't have to spend time working on features instead of getting the pr out the door if people are making the features for you *taps head*

void magnet lets you use the immortality talisman effect every minute, but constantly has a very low chance to activate randomly. This is mostly annoying but i could see some situations where the ability is on cooldown, you're cuffed... in a bad spot... you see what i mean.

fancy sprite made by my friend!

### CODE REVIEW

**Comment by Time-Green** [comment]
I love it. Do you mind me tweaking the chance of random triggering to use stability?

**Comment by tralezab** [comment]
Wouldn't mind at all, go for it

**Comment by Time-Green** [comment]
Thanks a ton for doing this, it makes everything a little cooler

**Comment by tralezab** [comment]
👍

**Pull request merged**
